matrix:
  include:
  - services: docker
    os: linux
    dist: trusty
    language: python
    sudo: required
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - services: docker
    os: linux
    dist: trusty
    language: python
    sudo: required
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
  - os: linux
    dist: trusty
    python: 3.6
    language: python
    compiler: clang-4.0
    env: CC='clang-4.0'
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        - ubuntu-toolchain-r-test
        packages: clang-4.0
    cache:
      directories: "$HOME/.cache/pip"
  - os: linux
    dist: trusty
    python: 3.5
    language: python
    cache:
      directories: "$HOME/.cache/pip"
    compiler: gcc-6
    env: CC='gcc-6'
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - g++-6
    cache:
      directories: "$HOME/.cache/pip"
  - os: osx
    osx_image: xcode6.4
    language: generic
    cache:
      directories:
        - "$HOME/.cache/pip"
        - "$HOME/Library/Caches/Homebrew"
  - os: osx
    osx_image: xcode7.3
    language: generic
    cache:
      directories:
        - "$HOME/.cache/pip"
        - "$HOME/Library/Caches/Homebrew"
  - os: osx
    osx_image: xcode8.3
    language: generic
    env: SOURCE=TRUE
    cache:
      directories:
        - "$HOME/.cache/pip"
        - "$HOME/Library/Caches/Homebrew"
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install python3 || brew
  upgrade python3; fi
- if [[ -n "$DOCKER_IMAGE" ]]; then docker pull $DOCKER_IMAGE; else pip3 install -U setuptools cython cyrandom; fi
install: if [[ -z "$DOCKER_IMAGE" ]]; then python3 setup.py install; else docker run
  --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/manylinux-build.sh; fi
script: if [[ -z "$DOCKER_IMAGE" ]]; then python3 test/test_pogeo.py; else ls wheelhouse/*; fi
deploy:
  provider: script
  script: travis/deploy.sh
  on:
    tags: true
    condition: -n "$DOCKER_IMAGE" || "$TRAVIS_OS_NAME" == "osx"
env:
  global:
    - secure: iJ/9icCGWr5lgu6EBg8fModQqVyN0Rn4NS39yXdq02pFH4na71kk9tI2aQUWyVHHVPYURWpLlFY0uFG/vX5DA5JyZG7zcqXfkN7eKiqBnQpAsrnen6s0sEx0KMb54YIMVW8N660t/xVIk4LVlvSMCZOEwXy1CZEfYnXntdGVcn1VdKr/bS4aXQ+xq2zYsMAIeSTkNVPfdmQ4aY4avMuSEBnc/Am59clAZYIj5aQuUmUDwQIBlLktla77aKMjbaCG/C+E5fKHk+J0AC4C4b9Rugew0AqIXcIQN7tmsCbwco3YZ+jNSWzntDYb9EclPvlqrxHI+L/2fPqZLdbaMHpGJ8j4hxczr819EbjCMBWX5Ed65gxutAEv9vyEvxIFXAY8dmX3oOq2G/Hfeg4BBK/Lw9ue9KHQ0YygIVCGBYMR/T47cUeD4G+sJcMhBZAwIHBGX1HN9h9qNubcYMyRD/dWw1Odu/ZarVwHf0E/M6YDXbyJ+N5hrHAbA1QMWooqJFNxeSbCDiyUi23pPjJVdsV6X0tavtykTcu3lNQTAmOk3tydJRSvrznY5v3GsVNMRmZlVgEHipTb6w4Gqx6onknsjHMCPpLB258GBfHvEXeuyyFKIj39xy9WMsIjKNjK7zL53V86+3n9ymza+yWygCU2otvjJ/soxTxiJMzLbsa7Meg=
    - TWINE_REPOSITORY: https://pypi.python.org/pypi
    - TWINE_REPOSITORY_URL: https://pypi.python.org/pypi
    - TWINE_USERNAME: Noctem
