secure: "o3Y+zClteHezpOGqPIHX7zI9WNscH0id4qAWC2B/Qn1zzflOftuqTtPt+/y9s2hUjzpU26BHNKaVUDZxWrGUA7QTDHHqeG3nZN51mhhmLJVd/Yb9/0NkKc/0fX+AJcODTii617Nv6GA8LgJ2CO+XaQMuW68cySjhi8Y8onxwSMS93sxZALGwtq7/bn4Uk2AyWWCJKg6AO8MbtRXvGEgr5aZ7lF4ukL1xpK5y/k6RxM3FKQJEXnf4DRNp7gnFjLKspC524j6QwluqbK7Oy+Rrd63Ac4iat0oYzuxjICQNpXmxX9YyzXnq4lgyH8rx3uKZE0tEDn0y5ob6YWzRjwm3cv16k3J9JL3shFylrHpVWIj/hFpN0mhSTaoPBo0Kje2SzmD0OMA9b/C03KygTDZfkRZ0OxV6l9d2ooHJ4eEQrhyaRGeXBQYSYeuqoPkDxe3/xj7AI8ZTbmNGux1NXtygI7Q2+sTjqeGp5CgVDuexEpQv1Dm3MwJwa5xaxJQK/YagA2MfWsyMo6hZtXUSEQXb5gmEyBuw4DmvqHaN5qrEKTnaSyfT457S7RWLN3rjp4iPRab8txchxdLbs3aIR1F4fZDSTaaGrP+IjAhGScTDVek7Uid2X4ccvRbidLBFwPSXWmoEhr4m0DHIcoNz2zIvfo00vQVZYC1T8T6rgkXerwo="

matrix:
  include:
    - services: docker
      os: linux
      dist: trusty
      python: 3.6
      sudo: required
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      addons:
        apt:
          packages:
            - 'gnupg2'
    - os: linux
      dist: trusty
      python: 3.5
      language: python
      compiler: clang
      env: COMPILER='clang++-3.9'
      addons:
        apt:
          sources:
            - ['llvm-toolchain-trusty-3.9', 'ubuntu-toolchain-r-test']
          packages:
            - 'clang-3.9'
    - os: linux
      dist: trusty
      python: 3.6
      language: python
      compiler: g++
      env: COMPILER='g++-6'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - os: osx
      osx_image: xcode6.4
      language: generic
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8.2
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && -z "$DOCKER_IMAGE" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc "/usr/bin/${COMPILER}" 1; sudo update-alternatives --install /usr/bin/g++ g++ "/usr/bin/${COMPILER}" 1; export CC="${COMPILER}"; export CXX="${COMPILER}"; fi
  - if [[ -n "$DOCKER_IMAGE" ]]; then docker pull $DOCKER_IMAGE; fi
  - pip3 install -U setuptools

install: if [[ -z "$DOCKER_IMAGE" ]]; then python3 setup.py install; else docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/travis/manylinux-build.sh; fi

script: if [[ -z "$DOCKER_IMAGE" ]]; then python3 test.py; else ls wheelhouse/*; fi

deploy:
  provider: script
  script: travis/deploy.sh
  on:
    condition: '-n "$DOCKER_IMAGE" || "$TRAVIS_OS_NAME" == "osx"'
