matrix:
  include:
    - os: linux
      dist: trusty
      python: 3.5
      language: python
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
    - os: linux
      dist: trusty
      python: 3.6
      language: python
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8.2
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install python3; fi

install:
  - pip3 install -U setuptools wheel
  - python3 setup.py install

script: python3 test.py
